### ISSUE TITLE
Installation fails on Ubuntu

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/cf-units#162]
Hi,

    pip3 install cf-units

fails with

    Collecting cf-units
    Using cached cf-units-2.1.4.tar.gz (176 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lq68eqg_/cf-units/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lq68eqg_/cf-units/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lq68eqg_/cf-units/pip-egg-info
    cwd: /tmp/pip-install-lq68eqg_/cf-units/
    Complete output (123 lines):
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        return result
    
    def convert_float(Converter converter, float value):
        return cv_convert_float(converter.cconverter, value)
    
    def convert_floats(Converter converter, np.ndarray[np.float32_t] in_, np.ndarray[np.float32_t] out):
                                           ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:305:40: 'ndarray' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        return result
    
    def convert_float(Converter converter, float value):
        return cv_convert_float(converter.cconverter, value)
    
    def convert_floats(Converter converter, np.ndarray[np.float32_t] in_, np.ndarray[np.float32_t] out):
                                                                         ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:305:70: 'ndarray' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        return out
    
    def convert_double(Converter converter, double value):
        return cv_convert_double(converter.cconverter, value)
    
    def convert_doubles(Converter converter, np.ndarray[np.float64_t] in_, np.ndarray[np.float64_t] out):
                                            ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:312:41: 'ndarray' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
        return out
    
    def convert_double(Converter converter, double value):
        return cv_convert_double(converter.cconverter, value)
    
    def convert_doubles(Converter converter, np.ndarray[np.float64_t] in_, np.ndarray[np.float64_t] out):
                                                                          ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:312:71: 'ndarray' is not a type identifier
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    def convert_float(Converter converter, float value):
        return cv_convert_float(converter.cconverter, value)
    
    def convert_floats(Converter converter, np.ndarray[np.float32_t] in_, np.ndarray[np.float32_t] out):
        cv_convert_floats(converter.cconverter, <float*> in_.data, in_.size, <float*> out.data)
                                               ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:306:44: Python objects cannot be cast to pointers of primitive types
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    def convert_float(Converter converter, float value):
        return cv_convert_float(converter.cconverter, value)
    
    def convert_floats(Converter converter, np.ndarray[np.float32_t] in_, np.ndarray[np.float32_t] out):
        cv_convert_floats(converter.cconverter, <float*> in_.data, in_.size, <float*> out.data)
                                                                            ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:306:73: Python objects cannot be cast to pointers of primitive types
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    def convert_double(Converter converter, double value):
        return cv_convert_double(converter.cconverter, value)
    
    def convert_doubles(Converter converter, np.ndarray[np.float64_t] in_, np.ndarray[np.float64_t] out):
        cv_convert_doubles(converter.cconverter, <double*> in_.data, in_.size, <double*> out.data)
                                                ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:313:45: Python objects cannot be cast to pointers of primitive types
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
    
    def convert_double(Converter converter, double value):
        return cv_convert_double(converter.cconverter, value)
    
    def convert_doubles(Converter converter, np.ndarray[np.float64_t] in_, np.ndarray[np.float64_t] out):
        cv_convert_doubles(converter.cconverter, <double*> in_.data, in_.size, <double*> out.data)
                                                                              ^
    ------------------------------------------------------------
    
    cf_units/_udunits2.pyx:313:75: Python objects cannot be cast to pointers of primitive types
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lq68eqg_/cf-units/setup.py", line 125, in <module>
        [udunits_ext] = cythonize(udunits_ext,
      File "/home/forecaster/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
        cythonize_one(*args)
      File "/home/forecaster/.local/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
        raise CompileError(None, pyx_file)
    Cython.Compiler.Errors.CompileError: cf_units/_udunits2.pyx
    Compiling cf_units/_udunits2.pyx because it depends on /home/forecaster/.local/lib/python3.8/site-packages/Cython/Includes/libc/__init__.pxd.
    [1/1] Cythonizing cf_units/_udunits2.pyx
    ----------------------------------------
    ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I tried to install udunits2 both via

    sudo apt-get install libudunits2-dev

as well as manually via

    sudo -s -H    
    cd /usr/local/src
    wget ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.28.tar.gz
    tar -xzf udunits-2.2.28.tar.gz
    cd udunits-2.2.28
    ./configure
    make
    make check
    make install
    make clean
    echo 'export UDUNITS2_XML_PATH=/usr/local/src/udunits-2.2.28/lib/udunits2.xml' >> ~/.bashrc
    source ~/.bashrc

What am I doing wrong?

**Comment by MHBalsmeier** [comment]
I set up a new VM and reinstalled everything and cf-units works fine.
I think the problem is that you should install udunits2 with apt and not manually.
I am closing this, since it does not seem to be a widestpread problem.
