### ISSUE TITLE
Installation problem on Ubuntu

### ISSUE THREAD

**Issue by MHBalsmeier** [SciTools/cf-units#199]
Hi,

I have run into a problem trying to install cf-units on Ubuntu. I did

```
sudo apt-get install libudunits2-dev libcunit1
pip3 install cf-units
```

and got

```
 ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmph0k6pzzu
       cwd: /tmp/pip-install-t4il548h/cf-units_cd399d2aa959496dacc627f74a0f3af9
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/ubuntu/.local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-un9p0y8c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 221, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-un9p0y8c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 207, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-un9p0y8c/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 150, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 152, in <module>
      package_data=get_package_data(),
    File "setup.py", line 75, in get_package_data
      raise ValueError(emsg)
  ValueError: Require to set UDUNITS2_XML_PATH for a cf-units wheel build.
  ----------------------------------------
  ERROR: Failed building wheel for cf-units
```
With `cf-units==3.0.1` it works.

OS: Ubuntu 20.04

**Comment by ocefpaf** [comment]
@MHBalsmeier try to set the environment variables for your udunits2, something like:

```
export UDUNITS2_INCDIR="/usr/include/udunits2"
export UDUNITS2_LIBDIR="/usr/lib64"
export UDUNITS2_XML_PATH="/usr/share/udunits/udunits2.xml"
```

PS: I don't understand how `pip` works but you should be getting the wheel instead of building from source when installing the latest version :-/

**Comment by MHBalsmeier** [comment]
Thanks, that worked. Weird that I had to do this with this version but never before.
