### ISSUE TITLE
netcdf4 1.2.7 breaks date comparison for some calendars

### ISSUE THREAD

**Issue by tv3141** [SciTools/cf-units#75]
`SciTools/Iris` has `cf_units` as dependency. The versions `1.9.2`, `1.10`, `1.11` on the conda-forge channel use netcdf4 1.2.7 and date comparison is broken for some calendars, see below.

Iris `1.12` uses netcdt4 1.2.4 and the tests below succeed.

```python
"""test_netcdf4_date_comparisons.py """
from datetime import datetime

from iris.time import PartialDateTime
import cf_units
import pytest


class Test_comparison_with_netcdftime():

    @pytest.mark.parametrize(
        'calendar',
        ['gregorian', 'standard', 'proleptic_gregorian', '360_day', 'julian',
         'noleap', '365_day', 'all_leap', '366_day']
    )
    def test_datetime(self, calendar):
        unit = 'days since 2000-01-01 00:00'
        time_unit = cf_units.Unit(unit, calendar)
        assert time_unit.num2date(10) < datetime(2001, 1, 1)


    @pytest.mark.parametrize(
        'calendar',
        ['gregorian', 'standard', 'proleptic_gregorian', '360_day', 'julian',
         'noleap', '365_day', 'all_leap', '366_day']
    )
    def test_partialdatetime(self, calendar):
        unit = 'days since 2000-01-01 00:00'
        time_unit = cf_units.Unit(unit, calendar)
        assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
```

```
> py.test --tb=native test_netcdf4_date_comparisons.py 
============================================================================================== test session starts ===============================================================================================
platform linux2 -- Python 2.7.13, pytest-2.9.2, py-1.4.32, pluggy-0.3.1
rootdir: /data/local/tvoigt/autoassess_upgrade, inifile: 
plugins: xdist-1.15.0, cov-2.4.0
collected 18 items 

tests/test_netcdf4_date_comparisons.py ...FFFFFF...FFFFFF

==================================================================================================== FAILURES ====================================================================================================
_____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[360_day] _____________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.Datetime360Day(2000, 1, 11, 0, 0, 0, 0, -1, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
_____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[julian] ______________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.DatetimeJulian(2000, 1, 11, 0, 0, 0, 0, -1, 1) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
_____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[noleap] ______________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.DatetimeNoLeap(2000, 1, 11, 0, 0, 0, 0, 3, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
_____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[365_day] _____________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.DatetimeNoLeap(2000, 1, 11, 0, 0, 0, 0, 3, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[all_leap] _____________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.DatetimeAllLeap(2000, 1, 11, 0, 0, 0, 0, 5, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
_____________________________________________________________________________ Test_comparison_with_netcdftime.test_datetime[366_day] _____________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 18, in test_datetime
    assert time_unit.num2date(10) < datetime(2001, 1, 1)
  File "netcdftime/_netcdftime.pyx", line 1292, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23305)
TypeError: cannot compare netcdftime._netcdftime.DatetimeAllLeap(2000, 1, 11, 0, 0, 0, 0, 5, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)
_________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[360_day] __________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.Datetime360Day(2000, 1, 11, 0, 0, 0, 0, -1, 11) and PartialDateTime(year=2001, month=1, day=1)
__________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[julian] __________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.DatetimeJulian(2000, 1, 11, 0, 0, 0, 0, -1, 1) and PartialDateTime(year=2001, month=1, day=1)
__________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[noleap] __________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.DatetimeNoLeap(2000, 1, 11, 0, 0, 0, 0, 3, 11) and PartialDateTime(year=2001, month=1, day=1)
_________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[365_day] __________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.DatetimeNoLeap(2000, 1, 11, 0, 0, 0, 0, 3, 11) and PartialDateTime(year=2001, month=1, day=1)
_________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[all_leap] _________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.DatetimeAllLeap(2000, 1, 11, 0, 0, 0, 0, 5, 11) and PartialDateTime(year=2001, month=1, day=1)
_________________________________________________________________________ Test_comparison_with_netcdftime.test_partialdatetime[366_day] __________________________________________________________________________
Traceback (most recent call last):
  File "/data/local/tvoigt/autoassess_upgrade/tests/test_netcdf4_date_comparisons.py", line 29, in test_partialdatetime
    assert time_unit.num2date(10) < PartialDateTime(year=2001, month=1, day=1)
  File "netcdftime/_netcdftime.pyx", line 1295, in netcdftime._netcdftime.datetime.__richcmp__ (netcdftime/_netcdftime.c:23410)
TypeError: cannot compare netcdftime._netcdftime.DatetimeAllLeap(2000, 1, 11, 0, 0, 0, 0, 5, 11) and PartialDateTime(year=2001, month=1, day=1)
====================================================================================== 12 failed, 6 passed in 0.47 seconds =======================================================================================


>   ???
E   TypeError: cannot compare netcdftime._netcdftime.DatetimeAllLeap(2000, 1, 11, 0, 0, 0, 0, 5, 11) and datetime.datetime(2001, 1, 1, 0, 0) (different calendars)

```

**Comment by DPeterK** [comment]
This is [being dealt with](https://github.com/SciTools/conda-recipes-scitools/pull/229). As things stand we _very much recommend_ that you do not use the conda-forge channel, for reasons such as this. It is much better to stick with the scitools channel, although we hope to synchronise these channels in the future.

**Comment by ocefpaf** [comment]
> This is being dealt with. As things stand we very much recommend that you do not use the conda-forge channel, for reasons such as this.

Bare in mind that conda can break the pinning and pull any other version that is easier to satisfy, hence breaking `iris` in any channel. So even `scitools` might suffer from that when users are updating/installing other things in their envs.

> although we hope to synchronise these channels in the future.

That particular pin already exists for a while BTW. See https://github.com/conda-forge/iris-feedstock/blob/master/recipe/meta.yaml#L41
