### ISSUE TITLE
Rounding error in julian_day2date

### ISSUE THREAD

**Issue by adamcpovey** [SciTools/cf-units#77]
Giving a minimal example,
```python
from cf_units import julian_day2date
julian_day2date(2450022.5, "standard")
```
gives output,
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/povey/bin/anaconda3/lib/python3.5/site-packages/cf_units/__init__.py", line 593, in julian_day2date
    return netcdftime.DateFromJulianDay(julian_day, calendar)
  File "/home/povey/bin/anaconda3/lib/python3.5/site-packages/netcdftime/netcdftime.py", line 371, in DateFromJulianDay
    minute[0], second[0], microsecond[0])
ValueError: day is out of range for month
```

I'm using cf_units 1.1.3 for python 3.5 through conda-forge.

**Comment by pelson** [comment]
Raised upstream in https://github.com/Unidata/cftime/issues/49.

**Comment by bjlittle** [comment]
Closing this issue as it has been resolved through https://github.com/Unidata/cftime/issues/49
