### ISSUE TITLE
 assert(0 == _ut_unmap_symbol_to_unit(_ut_system, _c_char_p('Sv'), _UT_ASCII))

### ISSUE THREAD

**Issue by ghost** [SciTools/cf-units#86]
After importing cf

```
from cf.units import Units
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pau/glorious/packages/mynotebooks/mypy2venv/local/lib/python2.7/site-packages/cf/__init__.py", line 80, in <module>
    from .variable             import Variable
  File "/home/pau/glorious/packages/mynotebooks/mypy2venv/local/lib/python2.7/site-packages/cf/variable.py", line 19, in <module>
    from .cfdatetime   import dt
  File "/home/pau/glorious/packages/mynotebooks/mypy2venv/local/lib/python2.7/site-packages/cf/cfdatetime.py", line 25, in <module>
    from .units     import Units
  File "/home/pau/glorious/packages/mynotebooks/mypy2venv/local/lib/python2.7/site-packages/cf/units.py", line 218, in <module>
    assert(0 == _ut_unmap_symbol_to_unit(_ut_system, _c_char_p('Sv'), _UT_ASCII))
AssertionError
```

I have these packages installed in a encapsulated virtual environment

backports.functools-lru-cache==1.5
cf-python==2.1.6
cycler==0.10.0
kiwisolver==1.0.1
matplotlib==2.2.2
netCDF4==1.3.1
numpy==1.14.2
psutil==5.4.3
pyparsing==2.2.0
python-dateutil==2.7.0
pytz==2018.3
scipy==1.0.0
six==1.11.0
subprocess32==3.2.7

I am wondering if you could deliver a compatible full virtual portable environment with all the dependencies installed? maybe that would make the whole thing easier...

**Comment by ajdawson** [comment]
Hi there @paugallesisardsat.

The problem you are reporting comes the [cf-python](https://cfpython.bitbucket.io/) library. This issue tracker is for an entirely separate project named `cf_units` (confusing names, I know...).

You should report your bug on the [cf-python issue tracker](https://bitbucket.org/cfpython/cf-python/issues?status=new&status=open). Good luck!

**Comment by ghost** [comment]
Oh, I see! thanks!
I posted the issue in their repo. It is in:
https://bitbucket.org/cfpython/cf-python/issues/39/assertion-error-on-cf-unitpy
